// components/ModelList.vue
<template>
  <ul>
    <li v-for="model in models" :key="model.title">
      <ModelItem
        :src="model.src"
        :iosSrc="model.iosSrc"
        :title="model.alt"
      />
    </li>
  </ul>
</template>

<script>
import '@google/model-viewer/dist/model-viewer'
import { defineComponent } from '@vue/composition-api'
import ModelItem from '@/components/ModelItem'
import data from '@/data/data.json'
export default defineComponent({
  components: {
    ModelItem
  },
  setup () {
    const models = data.models
    console.log(models)
    return {
      models
    }
  }
})
</script>

<style>
</style>

// components/ModelList.jsx
import ModelItem from '../components/ModelItem'
import data from '../data/data.json'

const ModelList = () => {
  return (
    <ul>
      {data.models.map((d, idx) => {
        return <ModelItem key={idx}
          iosSrc={d.iosSrc}
          src={d.src}
          alt={d.alt}
        />
      })}
    </ul>
  )
}
export default ModelList
