// components/ModelItem.jsx
import ModelView from '../components/ModelView'
import ModelInfo from '../components/ModelInfo'

const ModelItem = (props) => (
  <div>
    <ModelView
      params={{
        src: props.src,
        iosSrc: props.iosSrc,
        alt: props.alt
      }}
    />
    <ModelInfo
      title={props.alt}
    />
  </div>
)

export default ModelItem

// components/ModelItem.vue
<template>
  <div>
    <ModelView
      :src="src"
      :iosSrc="iosSrc"
      :title="title"
    />
    <ModelInfo
      :title="title"
    />
  </div>
</template>

<script>
import '@google/model-viewer/dist/model-viewer'
import { defineComponent } from '@vue/composition-api'
import ModelView from '@/components/ModelView'
import ModelInfo from '@/components/ModelInfo'

export default defineComponent({
  props: {
    src: { required: true },
    iosSrc: { required: true },
    title: { required: true }
  },
  components: {
    ModelView,
    ModelInfo
  },
  setup (props) {
    return {
      props
    }
  }
})
</script>

<style>
</style>
